name = "hello-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

account_id = "1393a4b8ac9bc429259644464a7f874e"

[vars]
APP_NAME = "hello"

[[d1_databases]]
binding = "DB"
database_name = "hello_db"
database_id = "REPLACE_AFTER_D1_CREATE"
migrations_dir = "../db/migrations"
