name = "fotocity-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

account_id = "1393a4b8ac9bc429259644464a7f874e"

# Habilita workers.dev
workers_dev = true

# Rota customizada
[[routes]]
pattern = "api-fotocity.paulopina.com/*"
zone_name = "paulopina.com"

[vars]
APP_NAME = "fotocity"
# Credenciais - em produção use secrets: wrangler secret put AUTH_USER
AUTH_USER = "admin"
AUTH_PASS = "fotocity2024"

# R2 Bucket - habilite R2 no dashboard e descomente:
# [[r2_buckets]]
# binding = "PHOTOS"
# bucket_name = "fotocity-photos"

# KV para sessões
[[kv_namespaces]]
binding = "SESSIONS"
id = "716516f97f914f3aac5b37c5300ea3b0"
